# -*- coding: utf-8 -*-
"""언어치료 문장 카드 생성.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17BvtjGcrTKIh2qF2atSRVWoB87XKsctI
"""

!pip install streamlit pandas

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import random
# import pandas as pd
# 
# st.set_page_config(page_title="문장 카드 생성기", layout="centered")
# 
# # 데이터
# subjects = ["아이가", "엄마가", "아빠가", "친구가", "선생님이"]
# objects = ["공을", "책을", "가방을", "신발을", "장난감을"]
# verbs = ["들어요", "놓아요", "먹어요", "읽어요", "신어요", "벗어요"]
# places = ["집에서", "학교에서", "놀이터에서", "교실에서"]
# times = ["오늘", "어제", "내일"]
# 
# st.title("🗣️ 언어치료 문장 카드 생성기")
# 
# # Choose between generation and custom input
# mode = st.radio("문장 입력 방식 선택", ["자동 생성", "직접 입력"])
# 
# if mode == "자동 생성":
#     sentence_type = st.selectbox(
#         "문장 유형 선택",
#         ["2어절", "3어절", "4어절"]
#     )
# 
#     count = st.slider("문장 개수", 1, 10, 5)
# 
#     def make_sentence():
#         s = random.choice(subjects)
#         o = random.choice(objects)
#         v = random.choice(verbs)
#         t = random.choice(times + places)
# 
#         if sentence_type == "2어절":
#             return f"{o} {v}"
#         elif sentence_type == "3어절":
#             return f"{s} {o} {v}"
#         else:
#             return f"{t} {s} {o} {v}"
# 
#     if st.button("문장 생성하기"):
#         result = [make_sentence() for _ in range(count)]
#         df = pd.DataFrame({"문장": result})
#         st.dataframe(df)
#         # Add download button
#         csv = df.to_csv(index=False, encoding='utf-8-sig')
#         st.download_button(
#             label="CSV로 다운로드",
#             data=csv,
#             file_name=f"generated_sentences_{sentence_type}.csv",
#             mime="text/csv",
#         )
# 
# elif mode == "직접 입력":
#     st.header("나만의 문장 입력하기")
#     custom_sentences_input = st.text_area(
#         "여기에 문장을 한 줄에 하나씩 입력하세요.",
#         height=200,
#         placeholder="예시:\n나는 학교에 갑니다.\n엄마가 책을 읽어요.\n아빠가 밥을 먹어요."
#     )
#     if st.button("입력 문장 표시"):
#         if custom_sentences_input:
#             custom_sentences = custom_sentences_input.split('\n') # Split by newline
#             # Clean up empty strings or extra spaces from split
#             custom_sentences = [s.strip() for s in custom_sentences if s.strip()]
#             if custom_sentences:
#                 df_custom = pd.DataFrame({"사용자 입력 문장": custom_sentences})
#                 st.dataframe(df_custom)
#                 # Add download button for custom sentences
#                 csv_custom = df_custom.to_csv(index=False, encoding='utf-8-sig')
#                 st.download_button(
#                     label="CSV로 다운로드",
#                     data=csv_custom,
#                     file_name="custom_sentences.csv",
#                     mime="text/csv",
#                 )
#             else:
#                 st.warning("입력된 문장이 없습니다. 문장을 입력해주세요.")
#         else:
#             st.warning("입력된 문장이 없습니다. 문장을 입력해주세요.")

!streamlit run app.py & npx localtunnel --port 8501 --yes

"""### `localtunnel` 대신 `ngrok` 사용하기

`localtunnel`은 Colab 환경에서 사용자 입력(`Ok to proceed? (y)`)을 필요로 하기 때문에 앱을 실행하고 외부에서 접속하는 데 어려움이 있습니다. 대신 `ngrok`을 사용하여 Streamlit 앱을 외부에 노출하는 것이 더 안정적입니다.

`ngrok`을 사용하려면 먼저 `ngrok` 인증 토큰이 필요합니다. [ngrok 웹사이트](https://dashboard.ngrok.com/get-started/your-authtoken)에서 무료로 가입하고 토큰을 발급받을 수 있습니다.

**경고:** `ngrok` 토큰은 민감한 정보이므로 직접 코드에 노출하지 않는 것이 좋습니다. Colab의 '비밀(Secrets)' 기능을 사용하여 안전하게 저장하고 사용하세요. (왼쪽 패널의 열쇠 아이콘 클릭 후 `NGROK_AUTH_TOKEN`이라는 이름으로 토큰을 저장)
"""