# -*- coding: utf-8 -*-
"""언어치료2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fhVz6ZQZbItOp5gJGD2sb9H2nXNOBe33
"""

# 1. 필수 라이브러리 설치
!pip install -q streamlit google-generativeai locales-korean

# 2. app.py 파일 생성 (이 코드가 나중에 깃허브에 올라갈 핵심 코드입니다)
# %%writefile 명령어는 아래 내용을 app.py라는 파일로 저장해줍니다.
with open('app.py', 'w', encoding='utf-8') as f:
    f.write('''
import streamlit as st
import google.generativeai as genai

# 페이지 설정
st.set_page_config(page_title="언어치료 AI 파트너", page_icon="🗣️")
st.title("🗣️ 언어치료 AI 파트너")
st.info("언어치료사를 위한 일지 초안 및 자극 자료 생성기입니다.")

# API 키 설정 (Streamlit Secrets에서 가져오기)
# 실제 배포 시에는 Streamlit Cloud 설정에서 넣어야 합니다.
if "GEMINI_API_KEY" in st.secrets:
    genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
else:
    st.warning("Streamlit Secrets에 GEMINI_API_KEY가 없습니다. 로컬 테스트용으로 진행하세요.")

model = genai.GenerativeModel('gemini-1.5-flash')

# 탭 구성
tab1, tab2 = st.tabs(["📝 일지 초안 만들기", "💡 언어 자극 생성"])

with tab1:
    st.subheader("오늘의 세션 요약")
    raw_note = st.text_area("활동 내용을 자유롭게 적어주세요.",
                            placeholder="예: 아이와 'ㄹ' 발음 연습함. '오리'를 '오디'로 발음함. 사탕 강화물을 사용하니 참여도 높음.")

    if st.button("일지 초안 생성"):
        if raw_note:
            prompt = f"당신은 전문 언어치료사입니다. 다음 활동 요약을 바탕으로 전문적인 SOAP(Subjective, Objective, Assessment, Plan) 형식의 치료 일지 초안과 부모님께 전달할 따뜻한 알림장 내용을 한국어로 작성해줘: {raw_note}"
            with st.spinner("전문적인 일지를 작성 중입니다..."):
                response = model.generate_content(prompt)
                st.markdown("---")
                st.markdown(response.text)
        else:
            st.error("내용을 입력해주세요.")

with tab2:
    st.subheader("맞춤형 언어 자극 생성")
    target = st.text_input("목표 음소나 주제를 입력하세요.", placeholder="예: 'ㄹ' 받침 단어, 감정 관련 형용사")

    if st.button("자료 생성"):
        if target:
            prompt = f"언어치료 세션에서 사용할 {target}에 관한 단어 리스트 10개와 이를 활용한 짧은 연습 문장 5개를 아이들 수준에 맞춰서 만들어줘."
            with st.spinner("자료 생성 중..."):
                response = model.generate_content(prompt)
                st.success("추천 자료가 생성되었습니다.")
                st.write(response.text)
        else:
            st.error("목표를 입력해주세요.")
    ''')

# 3. requirements.txt 파일 생성 (깃허브 업로드용)
with open('requirements.txt', 'w') as f:
    f.write('streamlit\ngoogle-generativeai')

print("✅ app.py와 requirements.txt 파일 생성 완료!")

# 로컬 터널을 이용해 스트림릿 실행 (코랩 환경용)
!npm install -g localtunnel
import subprocess
import threading

def run_streamlit():
    subprocess.run(["streamlit", "run", "app.py", "--server.port", "8501"])

thread = threading.Thread(target=run_streamlit)
thread.start()

# 이 코드를 실행하면 나오는 URL을 클릭하세요. (endpoint IP는 코랩의 외부 IP를 입력)
!npx localtunnel --port 8501